// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pokeymanz.Data;

#nullable disable

namespace Pokeymanz.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260215194112_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pokeymanz.Models.Entities.Pokeyman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("AvailableAttacks")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EggGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("EquippedAttacks")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("text[]");

                    b.Property<string>("HeldItem")
                        .HasColumnType("text");

                    b.Property<decimal>("Level")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Types")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Pokeymanz");
                });
#pragma warning restore 612, 618
        }
    }
}
